### ISSUE TITLE
License

### ISSUE THREAD

**Issue by papyr** [EasyAbp/EasyAbpGuide#1]
Hello I want use this commercially and also support your development.

AspNetZero is very very expensive and gettign more expensive, if you have a similar service on that I would be will to buy the license for 50 to 100$ for UI and modules.

Do you have social media/elgg like module

thanks

**Comment by gdlcf88** [comment]
Hi @papyr, thanks for the great confidence you have in us.

> if you have a similar service on that I would be will to buy the license for 50 to 100$ for UI and modules.

At present, we are only an open source organization and have no plans for commercial services.

> Do you have social media/elgg like module

No plan for now, but maybe in the future.

**Comment by papyr** [comment]
ok, great job!

Please do consider it as an alternative / there is a need out there
