### ISSUE TITLE
请问，还有机会加入贵组织吗？

### ISSUE THREAD

**Issue by afresh** [EasyAbp/EasyAbpGuide#17]
EasyAbp 团队，你们好！
本人使用aspnetboilerplate框架有三年的工作经验，使用abpframework也有半年的经验了，目前在用abp写一个微服务项目，最近还翻译了一些[abp官方文档](https://docs.abp.io/zh-Hans/abp/latest/Modules/Tenant-Management)。
今天无意间了解了一些贵组织的项目，我对贵组织非常感兴趣！不知道有没有机会能够成为贵组织的一员？

如有机会，请联系我：danding_ge@qq.com。

谢谢！

**Comment by hueifeng** [comment]
@afresh 你好，afresh！对于你的选择，我们感到很高兴，我们也希望越来越多的人加入Easy，一起来做更多的项目，提供更多的支持，为组织发挥更大的价值。但，对于目前而言，我们必须要确定的是你想参与哪一方面（比如特长？），这样也方便我们对您有一个了解，同时合理的对项目或组织各方面提供最大化的支持。

**Comment by afresh** [comment]
@hueifeng 您好，很高兴收到您的答复！
我其实没有什么特别擅长的，我觉得我最大的优势是学习能力和解决问题的能力。
就我个人的项目经验还有我公司目前的需求而言，我对 `Abp.WeChat` 项目和微服务相关的项目比较感兴趣，我想在工作的同时能够学习使用EasyAbp的一些模块，并为贵组织贡献代码。
使用和学习ABP框架并扩展一些功能模块也是我的长期计划。

**Comment by hueifeng** [comment]
@afresh 太好了，我们也是比较注重个人的想法和兴趣，我想你是不是可以先从你感兴趣的方面开始？比如说看一下模块项目中有哪些需要完善，或者说个人有什么想法，都是可以的。

**Comment by afresh** [comment]
@hueifeng 好的，我明白了。我会先尝试提一些pr😄
